use AISDraft;

LOAD DATA INFILE '/var/lib/mysql-files/VESSEL.csv' INTO TABLE AISDraft.VESSEL COLUMNS TERMINATED BY ',' IGNORE 1 ROWS;
LOAD DATA INFILE '/var/lib/mysql-files/MAP_VIEW.csv' INTO TABLE AISDraft.MAP_VIEW COLUMNS TERMINATED BY ',' IGNORE 1 ROWS;
LOAD DATA INFILE '/var/lib/mysql-files/PORT.csv' INTO TABLE AISDraft.PORT COLUMNS TERMINATED BY ';' IGNORE 1 ROWS;
LOAD DATA INFILE '/var/lib/mysql-files/AIS_MESSAGE_1000000_rows.csv' INTO TABLE AISDraft.AIS_MESSAGE COLUMNS TERMINATED BY ';' IGNORE 1 ROWS;
LOAD DATA INFILE '/var/lib/mysql-files/STATIC_DATA_1000000_rows.csv' INTO TABLE AISDraft.STATIC_DATA COLUMNS TERMINATED BY ';' IGNORE 1 ROWS;
LOAD DATA INFILE '/var/lib/mysql-files/POSITION_REPORT_1000000_rows.csv' INTO TABLE AISDraft.POSITION_REPORT COLUMNS TERMINATED BY ';' IGNORE 1 ROWS;